param(
    [string]$BaseUrl = "http://localhost:8080/api/v1"
)

$ErrorActionPreference = "Stop"
$api = $BaseUrl.TrimEnd('/')
$suffix = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
$templateCode = "SMOKE_$suffix"

function Invoke-Json {
    param(
        [Parameter(Mandatory = $true)][string]$Method,
        [Parameter(Mandatory = $true)][string]$Uri,
        [object]$Body
    )

    $parameters = @{
        Method = $Method
        Uri = $Uri
        ContentType = "application/json; charset=utf-8"
    }
    if ($null -ne $Body) {
        $json = $Body | ConvertTo-Json -Depth 12
        $parameters.Body = [Text.Encoding]::UTF8.GetBytes($json)
    }
    Invoke-RestMethod @parameters
}

Write-Host "1/9 Create template $templateCode"
$template = Invoke-Json -Method Post -Uri "$api/templates" -Body @{
    code = $templateCode
    name = "Smoke test template"
    description = "Generated by scripts/smoke-test.ps1"
}
$versionId = $template.currentVersionId

Write-Host "2/9 Create group and field"
$group = Invoke-Json -Method Post -Uri "$api/template-versions/$versionId/groups" -Body @{
    code = "GENERAL"
    label = "Thông tin chung"
    displayOrder = 1
    columnCount = 2
    collapsible = $false
    defaultCollapsed = $false
    repeatable = $false
}
Invoke-Json -Method Post -Uri "$api/template-versions/$versionId/fields" -Body @{
    groupId = $group.id
    fieldCode = "fullName"
    label = "Họ và tên"
    dataType = "STRING"
    componentType = "TEXT"
    required = $true
    searchable = $true
    sortable = $true
    exportable = $true
    maxLength = 255
    displayOrder = 1
    gridSpan = 6
    validations = @()
} | Out-Null

Write-Host "3/9 Validate metadata"
$validation = Invoke-Json -Method Post -Uri "$api/template-versions/$versionId/validate"
if (-not $validation.valid) {
    throw "Metadata validation failed: $($validation.errors | ConvertTo-Json -Depth 8)"
}

Write-Host "4/9 Generate and publish"
Invoke-Json -Method Post -Uri "$api/template-versions/$versionId/generate" | Out-Null
Invoke-Json -Method Post -Uri "$api/template-versions/$versionId/publish" | Out-Null

Write-Host "5/9 Create dynamic record"
$record = Invoke-Json -Method Post -Uri "$api/templates/$templateCode/records" -Body @{
    status = "COMPLETED"
    data = @{ fullName = "Nguyễn Văn Smoke" }
}

Write-Host "6/9 Search dynamic records"
$page = Invoke-Json -Method Post -Uri "$api/templates/$templateCode/records/search" -Body @{
    filters = @(@{ field = "fullName"; operator = "CONTAINS"; value = "Smoke" })
    sort = @(@{ field = "createdAt"; direction = "DESC" })
    page = 0
    size = 20
}
if ($page.totalElements -lt 1) {
    throw "Search did not return the created record"
}

Write-Host "7/9 Update with optimistic locking"
$record = Invoke-Json -Method Put -Uri "$api/templates/$templateCode/records/$($record.id)" -Body @{
    rowVersion = $record.rowVersion
    status = "COMPLETED"
    data = @{ fullName = "Nguyễn Văn Smoke Updated" }
}

Write-Host "8/9 Export XLSX"
$exportPath = Join-Path ([System.IO.Path]::GetTempPath()) "$templateCode.xlsx"
$exportBody = @{
    filters = @()
    sort = @(@{ field = "createdAt"; direction = "DESC" })
    page = 0
    size = 20
} | ConvertTo-Json -Depth 8
Invoke-WebRequest -Method Post -Uri "$api/templates/$templateCode/records/export" -ContentType "application/json; charset=utf-8" -Body ([Text.Encoding]::UTF8.GetBytes($exportBody)) -OutFile $exportPath
if ((Get-Item -LiteralPath $exportPath).Length -eq 0) {
    throw "Export file is empty"
}

Write-Host "9/9 Soft delete record"
Invoke-RestMethod -Method Delete -Uri "$api/templates/$templateCode/records/$($record.id)?rowVersion=$($record.rowVersion)" | Out-Null

Write-Host "Smoke test passed. Template: $templateCode"
Write-Host "Export file: $exportPath"
